probnik/Controllers/AlbumsController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using probnik.Models; // пространство имен моделей и контекста данных
using probnik.Data;
using System.Collections.Generic;
using System;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.IO;
using System.Security.Claims;

namespace probnik.Controllers
{
    public class AlbumsController : Controller
    {
        private ApplicationContext db;
        public AlbumsController(ApplicationContext context)
        {
            db = context;
        }

        public IActionResult Index()
        {
            /*var alboms = (from item in db.Albums.Include(x => x.Photos)
                          orderby item.Photos.albumId
                          select item).ToList();
            ViewBag.Count = db.Photos.ToList();

            return View(alboms.Distinct().ToList());
            */
            var idd = User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewBag.Count = db.Photos.ToList();
            ViewBag.Users = db.Users.Where(x => x.Id == idd).ToList();

            return View(db.Albums.Where(x => x.UserId == idd).OrderByDescending(x => x.Id).ToList());
        }
        public async Task<IActionResult> UsersAlbums(string? userId)
        {
            if (userId != null)
            {
                Albums album = await db.Albums.FirstOrDefaultAsync(p =>p.UserId==userId);
                    ViewBag.UserId = userId;
                    ViewBag.Count = db.Photos.ToList();
                    ViewBag.Users = db.Users.ToList();
                ViewBag.Albums = db.Albums.Where(x => x.UserId == userId).OrderByDescending(x => x.Id).ToList();
                ViewBag.Photos = db.Photos.ToList();

                return View();
            }
            return NotFound("ошибка");
        }
        public IActionResult Details(int? id)
        {
            if (id != null)
            {
                var details = (from item in db.Photos.Include(p => p.albums)
                               where item.albumId == id
                               select item).ToList();
                ViewBag.Albums = db.Albums.ToList();
                return View(details.OrderByDescending(x => x.Id).ToList());
            }
            return NotFound();
        }
        public IActionResult CreateAlbums()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateAlbums(Albums albums)
        {
            db.Albums.Add(albums);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public IActionResult CreatePhotos()
        {
            var idd = User.FindFirstValue(ClaimTypes.NameIdentifier);
            SelectList album = new SelectList(db.Albums.OrderByDescending(x => x.Id).Where(x=>x.UserId==idd), "Id", "Title");
            ViewBag.Album = album;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreatePhotos(Photos photos,PhotosViewModel pvm)
        {
            if (pvm.Photo != null)
            {
                byte[] imageData = null;
                // считываем переданный файл в массив байтов
                using (var binaryReader = new BinaryReader(pvm.Photo.OpenReadStream()))
                {
                    imageData = binaryReader.ReadBytes((int)pvm.Photo.Length);
                }
                // установка массива байтов
                photos.Photo = imageData;
            }
            db.Photos.Add(photos);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [HttpGet]
        [ActionName("DeleteAlbums")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                Albums albums = await db.Albums.FirstOrDefaultAsync(p => p.Photos.albumId == id);
                if (albums != null)
                    return View(albums);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> DeleteAlbums(int? id)
        {
            if (id != null)
            {
                IQueryable<Photos> photos = from o in db.Photos
                                            where o.albums.Id == id
                                            select o;
                Albums albums = db.Albums.Find(id);
                if (albums != null && photos != null)
                {
                    foreach (Photos od in photos)
                    {
                        db.Photos.Remove(od);
                    }
                    db.Albums.Remove(albums);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> DeletePhotos(int? id)
        {
            if (id != null)
            {
                Photos user = await db.Photos.FirstOrDefaultAsync(p => p.Id == id);
                if (user != null)
                {
                    db.Photos.Remove(user);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            return NotFound();
        }
    }
}

probnik/Controllers/MessagesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using probnik.Data;
using probnik.Models;
using probnik.ViewModels;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web.Helpers;
using probnik.Hubs;
using Microsoft.AspNetCore.SignalR;
using Microsoft.AspNetCore.Routing;

namespace probnik.Controllers
{

    public class MessegaseModel
    {
        public List<AddGroupChat> AddGroupChats { get; set; }
        public List<User> User { get; set; }

    }


    [Authorize]
    public class MessagesController : Controller
    {

        private readonly IHubContext<ChatsHub> hC;
        private ApplicationContext db;
        private readonly ILogger<MessagesController> _logger;
        UserManager<User> _userManager;
        RoleManager<IdentityRole> _roleManager;

        public MessagesController(ILogger<MessagesController> logger, ApplicationContext context, UserManager<User> userManager, RoleManager<IdentityRole> roleManager, IHubContext<ChatsHub> hubContext)
        {
            hC = hubContext;
            _logger = logger;
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            var id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var userName = User.Identity.Name;
            var list = db.AddGroupChat.ToList();
            var user = db.Users.ToList();
            //.Where(x => x.message != null)

            MessegaseModel model = new MessegaseModel()
            {
                AddGroupChats = list,
                User = user
            };
            ViewBag.Messages = db.Messages.ToList();
            //ViewBag.Users = db.Users.ToList();
            ViewBag.Photo = db.Messages.Select(x => x.Photo).ToList();
            ViewBag.AddGroupChat = db.AddGroupChat.Where(x => x.userId == id).ToList();
            ViewBag.GroupChat = db.GroupChat.ToList();
            return View(model);
        }   

        [Authorize]
        public IActionResult Message( string id, string name, string Email, byte[] photo)
        {
            
            if (id != null)
            {
                //Messages messages = await db.Messages
                //    .FirstOrDefaultAsync(p => p.id == id && p.user.Name == name && p.user.Email == Email && p.user.Photo == photo);
                //var only = User.Identity.Name;
                //var idd = User.FindFirstValue(ClaimTypes.NameIdentifier);
                //ViewBag.Message = db.Messages
                //    .Where(x => (x.id == id && x.Fromm == only) || (x.Fromm == Email && x.id == idd))
                //    .OrderBy(x => x.Date)
                //    .ToList();
                ViewBag.Users = db.Users
                    .Where(x => x.Id == id)
                    .ToList();
                ViewBag.Name = name;
                ViewBag.Email = Email;
                ViewBag.Mid = id;
                return View();
                
            }
            return NotFound();

        }
        [HttpPost]
        public async Task<ActionResult> sendMessages(Messages msg,string Email)
        {
            var idd = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var only = User.Identity.Name;
            var mes = db.Messages.ToList();
            if (msg.Message != null)
            {
                db.Messages.Add(msg);
            }
            await db.SaveChangesAsync();
            string messagee = "SUCCESS";
            return Json(new { Messagee = messagee, System.Web.Mvc.JsonRequestBehavior.AllowGet });

        }
        public  JsonResult getMessages(string id,string Email)
        {
            var only = User.Identity.Name;
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            List<Messages> messages = new List<Messages>();
            messages = db.Messages.ToList();
            return Json(messages.Where(x => (x.id == id && x.Fromm == only) || (x.Fromm == Email && x.id == userId)));
        }
        public IActionResult AddGroupChat()
        {
            var idd = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var only = User.Identity.Name;
            ViewBag.Friends = db.Friends.Where(x => x.Sender == idd||x.Recipient==idd).ToList();
            var friends= db.Friends.Where(x => x.Sender == idd || x.Recipient == idd).ToList();
            ViewBag.Users = db.Users.ToList();
            var Chat = db.AddGroupChat.ToList();
            if (Chat.Count() >= 1)
            {
                ViewBag.Chat = Chat.OrderBy(x => x.GroupId).LastOrDefault(x => x.GroupId != null).GroupId + 1;
            }
            else
            {
                ViewBag.Chat = 1;
            }

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddGroupChat(List<AddGroupChat> groupModels, string NameGroup, IFormFile updatedPhoto)
        {
            for (var i = 0; i < groupModels.Count(); i++)
            {
                if (updatedPhoto != null)
                {
                    byte[] imageData = null;
                    // считываем переданный файл в массив байтов
                    using (var binaryReader = new BinaryReader(updatedPhoto.OpenReadStream()))
                    {
                        imageData = binaryReader.ReadBytes((int)updatedPhoto.Length);
                    }
                    // установка массива байтов
                    groupModels[0].Photo = imageData;
                }
                groupModels[0].Role = groupModels[0].Role;
                groupModels[0].Name = NameGroup;
                if (groupModels[i].userId != null) 
                {
                db.AddGroupChat.AddRange(groupModels[i]);
                }

            }
            
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> EditGroupChat(long? groupId)
        {
            var idd = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (groupId != null)
            {
                AddGroupChat addGroupChat = await db.AddGroupChat.FirstOrDefaultAsync(p => p.GroupId == groupId);
                if (addGroupChat != null)
                {
                    ViewBag.GroupId = groupId;
                    ViewBag.UserId = groupId;
                    ViewBag.Users = db.Users.Where(x => x.AddGroupChats.GroupId == groupId).ToList();
                    ViewBag.Userss = db.Users.ToList();
                    ViewBag.AddGroupChat = db.AddGroupChat.Where(x => x.GroupId == groupId).ToList();
                    ViewBag.Friends = db.Friends.Where(x => x.Sender == idd || x.Recipient == idd).ToList();

                    return View(addGroupChat);
                }
            }
            return NotFound();
        }
        public async Task<ActionResult> editRole(long id,string mute="Mute")
        {
            AddGroupChat groupChat = db.AddGroupChat.FirstOrDefault(x => x.Id == id);
            groupChat.Role = mute;
            db.AddGroupChat.Update(groupChat);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> EditGroupChat(List<AddGroupChat> addGroupChat, string NameGroup, IFormFile updatedPhoto)
        {
            for (var i = 0; i < addGroupChat.Where(x => x.userId != null).Count(); i++)
            {
                if (updatedPhoto != null)
                {
                    byte[] imageData = null;
                    // считываем переданный файл в массив байтов
                    using (var binaryReader = new BinaryReader(updatedPhoto.OpenReadStream()))
                    {
                        imageData = binaryReader.ReadBytes((int)updatedPhoto.Length);
                    }
                    // установка массива байтов
                    addGroupChat[0].Photo = imageData;
                }
                addGroupChat[0].Role = addGroupChat[0].Role;
                addGroupChat[0].Name = NameGroup;
                db.AddGroupChat.UpdateRange(addGroupChat[i]); ;
            }
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> AddUserChat(List<AddGroupChat> addUserChat)
        {
            //for (var i = 0; i < addUserChat.Where(x => x.userId != null).Count(); i++)
            //{
            //    db.AddGroupChat.UpdateRange(addUserChat[i]); ;
            //}
            db.AddGroupChat.UpdateRange(addUserChat.Where(x=>x.userId!=null));
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> GroupMessage(long groupId, string Name)
        {
            if (groupId != null)
            {
                var idd = User.FindFirstValue(ClaimTypes.NameIdentifier);
                GroupChat groupChats = await db.GroupChat.FirstOrDefaultAsync(p => p.addGroupChat.GroupId == groupId && p.addGroupChat.Name == Name);

                ViewBag.GroupId = groupId;
                ViewBag.Name = Name;
                ViewBag.Id = db.AddGroupChat.OrderBy(x=>x.Id).FirstOrDefault(x => x.GroupId == groupId).Id;
                ViewBag.GroupChat = db.GroupChat.Where(x => x.addGroupChatId == groupId).ToList();
                ViewBag.AddGroupChat = db.AddGroupChat.Where(x => x.GroupId == groupId&&x.Name!=null).ToList();
                ViewBag.Mute = db.AddGroupChat.Where(x=> x.Role != "Mute" && x.userId == idd).ToList();
                ViewBag.Users = db.Users.ToList();

probnik/Views/Shared/_Layout.cshtml
@using System.Security.Claims;
@{
    var idd = User.FindFirstValue(ClaimTypes.NameIdentifier);
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="icon" href="https://sun9-77.userapi.com/impg/c857324/v857324279/1bc14c/_A2KCrKSmDA.jpg?size=604x587&quality=96&sign=d8cb68d743882097e8690e26c8da85fb&type=album" />
    <script src="https://kit.fontawesome.com/9a4928363c.js" crossorigin="anonymous"></script>
</head>
<style>
    a {
        color: rgb(108 108 255);
    }

    input[type='file'] {
        color: transparent;
    }

    .container a {
        text-decoration: none;
    }

    label {
        color: rgb(108 108 255);
    }

    h2 {
        color: rgb(108 108 255);
    }

    p {
        color: rgb(108 108 255);
    }

    .header__logo {
        flex: 0 0 60px;
        border-radius: 50%;
        overflow: hidden;
    }
    .rightbokmenu {
        position: fixed;
        height: 70px;
        width: 10%;
        background-color: rgba(128, 128, 255,0.3);
        right: 15%;
        top: 73px;
        border-radius: 10px;
        font-size:13px;
    }

    .header__logo img {
        max-width: 100%;
        display: block;
    }

    .bokmenu {
        height: 200px;
        width: 130px;
        position: absolute;
        display: flex;
        max-width: 25%;
        min-width: 10px;
        left: 13%;
        /*top: 11%;*/
        background-color: rgba(128, 128, 255,0.3);
        border-radius: 10px;
        max-height: 160px;
    }

    body {
        font-size: 15px;
    }

    .container {
        width: 41%;
    }

    input[type=submit] {
        border-radius: 10px;
        border-color: rgba(128, 128, 255,0.3);
        background: rgba(128 128 255 / 15%);
        justify-content: center;
        display: flex;
        flex-flow: row wrap;
    }

    @@media (max-width:1040px) {

        .bokmenu {
            width: 14%;
            font-size: 10px;
        }
    }

    @@media (max-width:900px) {
        .rightbokmenu {
            font-size:8px;
        }
    }

    @@media (max-width:600px) {
        .bokmenu {
            font-size: 8px;
        }
        .rightbokmenu{
        height:60px;
        }
        input[type=submit] {
            width: 40px;
            height: 20px;
            font-size: 7px;
        }

        .container {
            font-size: 8px;
        }
    }

    @@media (max-width:490px) {
        .container {
            width: 51%;
        }
        .rightbokmenu {
            right:10%;
            width:13%;
            height:50px;
            font-size:6px;
        }
            .bokmenu {
            left: 15px;
            width: 18%;
        }

        h2 {
            font-size: 15px;
        }

        input[type=submit] {
            width: 30px;
            height: 15px;
            font-size: 5px;
        }
    }
    @@media (max-width:420px) {
        .rightbokmenu {
            width:15%;
            right:8%;
        }
    }
</style>
<body style=" background: white;">
    <header>
        <nav style="border-bottom: 1px solid #b8cadc00 !important;background-color: rgba(128, 128, 255,0.3); width: 100%; " class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom  mb-3">
            <div class="container" style="width:100%;">
                <a class="navbar-brand" style="color: rgb(108 108 255);" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>

                @if (User.Identity.IsAuthenticated)
                {
                    <div style="position: absolute;right: 2%;">

                        <form method="post" asp-controller="Account" asp-action="Logout">
                            <span>
                                <div style="display: inline-block;">
                                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="UserId" asp-route-id="@idd">
                                        Моя страница
                                    </a>
                                </div>
                            </span>
                            <span>
                                <div style="display: inline-block;">
                                    <label class="upload-file__label" for="upload-file__input_output">
                                        <i class="fas fa-sign-out-alt"></i>
                                    </label>
                                    <input hidden id="upload-file__input_output" type="submit" value="Выход" />
                                </div>
                            </span>

                        </form>
                    </div>

                }
                else
                {
                    <div style="top: 28%;position: absolute;right: 2%;">
                        <a asp-controller="Account" asp-action="Login">Вход</a>
                        <a asp-controller="Account" asp-action="Register">Регистрация</a>
                    </div>
                }
            </div>
        </nav>
    </header>
    @if (User.Identity.IsAuthenticated)
    {

        <div class="bokmenu" align="left">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">

                    <a class="nav-link" style="margin-left:5px;" asp-area="" asp-controller="Home" asp-action="Friends"><i class="fas fa-user-friends"></i> Друзья</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" style="margin-left:5px;" asp-area="" asp-controller="Messages" asp-action="Index"><i class="far fa-envelope"></i> Сообщения</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" style="margin-left:5px;" asp-area="" asp-controller="Albums" asp-action="Index"><i class="far fa-images"></i> Галерея</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" style="margin-left:5px;" asp-area="" asp-controller="Home" asp-action="GetUsers"><i class="fas fa-users"></i> Пользователи</a>
                </li>


            </ul>
        </div>
    }

    <div class="container" style=" border-radius: 10px; height: 100%; min-height: 525px; background-color: rgba(128, 128, 255,0.3); ">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>